// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj3dV_zOSqZ2dafFCMRk4dgcfZZb_lp88',
    appId: '1:237611904697:web:0290c23f914d1b4a3a3568',
    messagingSenderId: '237611904697',
    projectId: 'aflami-ecd95',
    authDomain: 'aflami-ecd95.firebaseapp.com',
    storageBucket: 'aflami-ecd95.appspot.com',
    measurementId: 'G-TC7RZL4TNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQUZNbJix1na1ixkk70G-6GtYxs5Vako',
    appId: '1:237611904697:android:e9c55ae4b2edba043a3568',
    messagingSenderId: '237611904697',
    projectId: 'aflami-ecd95',
    storageBucket: 'aflami-ecd95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBjT7LSfAmRLSD8k0r-i1_g6DoyW0IszU',
    appId: '1:237611904697:ios:590ee1e2004824b63a3568',
    messagingSenderId: '237611904697',
    projectId: 'aflami-ecd95',
    storageBucket: 'aflami-ecd95.appspot.com',
    iosBundleId: 'com.example.aflami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBjT7LSfAmRLSD8k0r-i1_g6DoyW0IszU',
    appId: '1:237611904697:ios:590ee1e2004824b63a3568',
    messagingSenderId: '237611904697',
    projectId: 'aflami-ecd95',
    storageBucket: 'aflami-ecd95.appspot.com',
    iosBundleId: 'com.example.aflami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj3dV_zOSqZ2dafFCMRk4dgcfZZb_lp88',
    appId: '1:237611904697:web:d7ae2720559657b33a3568',
    messagingSenderId: '237611904697',
    projectId: 'aflami-ecd95',
    authDomain: 'aflami-ecd95.firebaseapp.com',
    storageBucket: 'aflami-ecd95.appspot.com',
    measurementId: 'G-002DWL467S',
  );
}
